"""cria tabelas iniciais

Revision ID: 16f4a32ac67c
Revises: 
Create Date: 2026-07-06 10:11:21.698893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f4a32ac67c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('firmware_version', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_device_active', 'devices', ['active'], unique=False)
    op.create_index('ix_device_created_at', 'devices', ['created_at'], unique=False)
    op.create_index('ix_device_serial', 'devices', ['serial_number'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('alarm_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_acknowledged', 'alerts', ['acknowledged'], unique=False)
    op.create_index('ix_alert_device_created', 'alerts', ['device_id', 'created_at'], unique=False)
    op.create_index('ix_alert_level', 'alerts', ['level'], unique=False)
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_created', 'analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_device_id'), 'analytics', ['device_id'], unique=False)
    op.create_index('ix_analytics_device_metric', 'analytics', ['device_id', 'metric'], unique=False)
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_config_device_key', 'configurations', ['device_id', 'key'], unique=True)
    op.create_index(op.f('ix_configurations_device_id'), 'configurations', ['device_id'], unique=False)
    op.create_table('device_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('rssi', sa.Float(), nullable=True),
    sa.Column('uptime', sa.Float(), nullable=True),
    sa.Column('firmware_version', sa.String(length=20), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_status_device_id'), 'device_status', ['device_id'], unique=False)
    op.create_index('ix_devicestatus_device', 'device_status', ['device_id', 'status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_device_occurred', 'events', ['device_id', 'occurred_at'], unique=False)
    op.create_index('ix_event_type', 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_device_id'), 'events', ['device_id'], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('vibration_x', sa.Float(), nullable=True),
    sa.Column('vibration_y', sa.Float(), nullable=True),
    sa.Column('vibration_z', sa.Float(), nullable=True),
    sa.Column('rms', sa.Float(), nullable=True),
    sa.Column('peak', sa.Float(), nullable=True),
    sa.Column('kurtosis', sa.Float(), nullable=True),
    sa.Column('crest_factor', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sample_device_recorded', 'samples', ['device_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_samples_device_id'), 'samples', ['device_id'], unique=False)
    op.create_index(op.f('ix_samples_recorded_at'), 'samples', ['recorded_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_user_email', 'users', ['email'], unique=False)
    op.create_index('ix_user_username', 'users', ['username'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('details', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_log_level_created', 'logs', ['level', 'created_at'], unique=False)
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_device_id'), 'logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_device_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_index('ix_log_level_created', table_name='logs')
    op.drop_table('logs')
    op.drop_index('ix_user_username', table_name='users')
    op.drop_index('ix_user_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_samples_recorded_at'), table_name='samples')
    op.drop_index(op.f('ix_samples_device_id'), table_name='samples')
    op.drop_index('ix_sample_device_recorded', table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_events_device_id'), table_name='events')
    op.drop_index('ix_event_type', table_name='events')
    op.drop_index('ix_event_device_occurred', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_devicestatus_device', table_name='device_status')
    op.drop_index(op.f('ix_device_status_device_id'), table_name='device_status')
    op.drop_table('device_status')
    op.drop_index(op.f('ix_configurations_device_id'), table_name='configurations')
    op.drop_index('ix_config_device_key', table_name='configurations')
    op.drop_table('configurations')
    op.drop_index('ix_analytics_device_metric', table_name='analytics')
    op.drop_index(op.f('ix_analytics_device_id'), table_name='analytics')
    op.drop_index('ix_analytics_created', table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_index('ix_alert_level', table_name='alerts')
    op.drop_index('ix_alert_device_created', table_name='alerts')
    op.drop_index('ix_alert_acknowledged', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('roles')
    op.drop_index('ix_device_serial', table_name='devices')
    op.drop_index('ix_device_created_at', table_name='devices')
    op.drop_index('ix_device_active', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
