"""schema_inicial_completo

Revision ID: 4416750d8532
Revises: 
Create Date: 2026-07-16 11:47:53.957730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4416750d8532'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_site_id'), table_name='projects')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_site_id'), 'projects', ['site_id'], unique=False)
    # ### end Alembic commands ###
